version: '3.8'

services:
  backend:
    build: ./restaurantproj
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./restaurantproj:/app
    ports:
      - 8000:8000

  frontend:
    build: ./react_app
    volumes:
      - ./react_app:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
