services:
  database:
    image: postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/setup:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      # - POSTGRES_NAME=postgres
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
      - WAIT_HOSTS=database:5432
      - WAIT_TIMEOUT=180
    depends_on:
      - database
  frontend:
    image: node:lts-bullseye
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '5173:5173'
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: '0.0.0.0'
      PUBLIC_URL: http://localhost:5173
      DJANGO_API_HOST: http://localhost:8000
